import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="p-4 bg-gray-100">
          <ul className="flex space-x-4">
            <li>
              <a href="/" className="text-blue-500 hover:underline">
                Home
              </a>
            </li>
            <li>
              <a href="/env" className="text-blue-500 hover:underline">
                Environment
              </a>
            </li>
            <li><a href="/test" className="text-blue-500 hover:underline">PublicEnvTest</a></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
